---
- name: configure jenkins variables
  include_vars: "{{ jenkins_version }}.yml"
  tags:
  - packages
  - jenkins-plugins

- import_tasks: redhat.yml
- import_tasks: debian.yml

- name: ensure Jenkins is started/stopped
  service:
    name: jenkins
    state: started
    enabled: yes

- name: create jenkins-cli path
  file:
    path: "{{ jenkins_cli_path }}/"
    state: directory

- name: wait for Jenkins API to response properly
  uri:
    url: "{{ jenkins_cli_url }}/api/json"
    return_content: yes
  register: webpage
  until: webpage.status in [ 403, 200 ]
  failed_when: webpage.status not in [ 403, 200 ]
  retries: 10
  delay: 10

- name: install Jenkins cli
  get_url:
    url: "{{ jenkins_cli_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_path }}/jenkins-cli.jar"

- name: install Jenkins plugin helper script
  template:
    src: jenkins-plugins.j2
    dest: /usr/local/bin/jenkins-plugins
    mode: 0750
  tags:
  - jenkins-plugins

- name: get installed Jenkins plugins
  shell: /usr/local/bin/jenkins-plugins list
  register: jenkins_plugins_installed
  ignore_errors: yes
  changed_when: no
  check_mode: no
  tags:
  - jenkins-plugins

- name: Outdated plugins
  debug:
    var: jenkins_plugins_installed.stdout_lines

- name: install missing Jenkins plugins
  shell: /usr/local/bin/jenkins-plugins install {{ item }}
  notify: cli safe-restart jenkins
  loop: "{{ jenkins_plugins }}"
  when: jenkins_install_plugins == true and jenkins_plugins_installed is success and item not in jenkins_plugins_installed.stdout_lines
  tags:
  - jenkins-plugins

- name: check for Jenkins plugin updates
  command: /usr/local/bin/jenkins-plugins list-outdated
  register: plugins_to_update
  changed_when: no
  check_mode: no
  tags:
  - jenkins-plugins

- name: Outdated plugins
  debug:
    var: plugins_to_update.stdout_lines

- name: update outdated Jenkins plugins
  shell: /usr/local/bin/jenkins-plugins install {{ item }}
  notify: cli safe-restart jenkins
  loop: "{{ plugins_to_update.stdout_lines }}"
  when: jenkins_update_plugins == true and plugins_to_update is success
  tags:
  - jenkins-plugins
